export const moviesList = [
  {
    title: "Can't Stop the Music",
    year: 1980,
    award: true,
    studio: 'associated film distribution',
    producers: ['allan carr'],
  },
  {
    title: 'Cruising',
    year: 1980,
    award: false,
    studio: 'lorimar productions, united artists',
    producers: ['jerry weintraub'],
  },
  {
    title: 'The Formula',
    year: 1980,
    award: false,
    studio: 'mgm, united artists',
    producers: ['steve shagan'],
  },
  {
    title: 'Friday the 13th',
    year: 1980,
    award: false,
    studio: 'paramount pictures',
    producers: ['sean s. cunningham'],
  },
  {
    title: 'The Nude Bomb',
    year: 1980,
    award: false,
    studio: 'universal studios',
    producers: ['jennings lang'],
  },
  {
    title: 'The Jazz Singer',
    year: 1980,
    award: false,
    studio: 'associated film distribution',
    producers: ['jerry leider'],
  },
  {
    title: 'Raise the Titanic',
    year: 1980,
    award: false,
    studio: 'associated film distribution',
    producers: ['william frye'],
  },
  {
    title: 'Saturn 3',
    year: 1980,
    award: false,
    studio: 'associated film distribution',
    producers: ['stanley donen'],
  },
  {
    title: 'Windows',
    year: 1980,
    award: false,
    studio: 'united artists',
    producers: ['mike lobell'],
  },
  {
    title: 'Xanadu',
    year: 1980,
    award: false,
    studio: 'universal studios',
    producers: ['lawrence gordon'],
  },
  {
    title: 'Mommie Dearest',
    year: 1981,
    award: true,
    studio: 'paramount pictures',
    producers: ['frank yablans'],
  },
  {
    title: 'Endless Love',
    year: 1981,
    award: false,
    studio: 'universal studios, polygram',
    producers: ['dyson lovell'],
  },
  {
    title: "Heaven's Gate",
    year: 1981,
    award: false,
    studio: 'united artists',
    producers: ['joann carelli'],
  },
  {
    title: 'The Legend of the Lone Ranger',
    year: 1981,
    award: false,
    studio: 'universal studios, associated film distribution',
    producers: ['walter coblenz'],
  },
  {
    title: 'Tarzan, the Ape Man',
    year: 1981,
    award: false,
    studio: 'mgm, united artists',
    producers: ['john derek'],
  },
  {
    title: 'Inchon',
    year: 1982,
    award: true,
    studio: 'mgm',
    producers: ['mitsuharu ishii'],
  },
  {
    title: 'Annie',
    year: 1982,
    award: false,
    studio: 'columbia pictures',
    producers: ['ray stark'],
  },
  {
    title: 'Butterfly',
    year: 1982,
    award: false,
    studio: 'analysis film releasing',
    producers: ['matt cimber'],
  },
  {
    title: 'Megaforce',
    year: 1982,
    award: false,
    studio: '20th century fox',
    producers: ['albert s. ruddy'],
  },
  {
    title: 'The Pirate Movie',
    year: 1982,
    award: false,
    studio: '20th century fox',
    producers: ['david joseph'],
  },
  {
    title: 'The Lonely Lady',
    year: 1983,
    award: true,
    studio: 'universal studios',
    producers: ['robert r. weston'],
  },
  {
    title: 'Hercules',
    year: 1983,
    award: false,
    studio: 'mgm, united artists, cannon films',
    producers: ['yoram globus', 'menahem golan'],
  },
  {
    title: 'Jaws 3-D',
    year: 1983,
    award: false,
    studio: 'universal studios',
    producers: ['rupert hitzig'],
  },
  {
    title: 'Stroker Ace',
    year: 1983,
    award: false,
    studio: 'warner bros., universal studios',
    producers: ['hank moonjean'],
  },
  {
    title: 'Two of a Kind',
    year: 1983,
    award: false,
    studio: '20th century fox',
    producers: ['roger m. rothstein', 'joe wizan'],
  },
  {
    title: 'Bolero',
    year: 1984,
    award: true,
    studio: 'cannon films',
    producers: ['bo derek'],
  },
  {
    title: 'Cannonball Run II',
    year: 1984,
    award: false,
    studio: 'warner bros.',
    producers: ['albert s. ruddy'],
  },
  {
    title: 'Rhinestone',
    year: 1984,
    award: false,
    studio: '20th century fox',
    producers: ['marvin worth', 'howard smith'],
  },
  {
    title: 'Sheena',
    year: 1984,
    award: false,
    studio: 'columbia pictures',
    producers: ['paul aratow'],
  },
  {
    title: "Where the Boys Are '84",
    year: 1984,
    award: false,
    studio: 'tristar pictures',
    producers: ['allan carr'],
  },
  {
    title: 'Rambo: First Blood Part II',
    year: 1985,
    award: true,
    studio: 'columbia pictures',
    producers: ['buzz feitshans'],
  },
  {
    title: 'Fever Pitch',
    year: 1985,
    award: false,
    studio: 'mgm, united artists',
    producers: ['freddie fields'],
  },
  {
    title: 'Revolution',
    year: 1985,
    award: false,
    studio: 'warner bros.',
    producers: ['irwin winkler'],
  },
  {
    title: 'Rocky IV',
    year: 1985,
    award: false,
    studio: 'mgm, united artists',
    producers: ['irwin winkler', 'robert chartoff'],
  },
  {
    title: 'Year of the Dragon',
    year: 1985,
    award: false,
    studio: 'mgm, united artists',
    producers: ['dino de laurentiis'],
  },
  {
    title: 'Howard the Duck',
    year: 1986,
    award: true,
    studio: 'universal studios',
    producers: ['gloria katz'],
  },
  {
    title: 'Under the Cherry Moon',
    year: 1986,
    award: true,
    studio: 'warner bros.',
    producers: ['bob cavallo', 'joe ruffalo', 'steve fargnoli'],
  },
  {
    title: 'Blue City',
    year: 1986,
    award: false,
    studio: 'paramount pictures',
    producers: ['william l. hayward', 'walter hill'],
  },
  {
    title: 'Cobra',
    year: 1986,
    award: false,
    studio: 'warner bros., cannon films',
    producers: ['yoram globus', 'menahem golan'],
  },
  {
    title: 'Shanghai Surprise',
    year: 1986,
    award: false,
    studio: 'mgm',
    producers: ['john kohn'],
  },
  {
    title: 'Leonard Part 6',
    year: 1987,
    award: true,
    studio: 'columbia pictures',
    producers: ['bill cosby'],
  },
  {
    title: 'Ishtar',
    year: 1987,
    award: false,
    studio: 'columbia pictures',
    producers: ['warren beatty'],
  },
  {
    title: 'Jaws: The Revenge',
    year: 1987,
    award: false,
    studio: 'universal studios',
    producers: ['joseph sargent'],
  },
  {
    title: "Tough Guys Don't Dance",
    year: 1987,
    award: false,
    studio: 'cannon films',
    producers: ['yoram globus', 'menahem golan'],
  },
  {
    title: "Who's That Girl",
    year: 1987,
    award: false,
    studio: 'warner bros.',
    producers: ['rosilyn heller', 'bernard williams'],
  },
  {
    title: 'Cocktail',
    year: 1988,
    award: true,
    studio: 'touchstone pictures',
    producers: ['ted field', 'robert w. cort'],
  },
  {
    title: 'Caddyshack II',
    year: 1988,
    award: false,
    studio: 'warner bros.',
    producers: ['neil canton', 'jon peters', 'peter guber'],
  },
  {
    title: 'Hot to Trot',
    year: 1988,
    award: false,
    studio: 'warner bros.',
    producers: ['steve tisch'],
  },
  {
    title: 'Mac and Me',
    year: 1988,
    award: false,
    studio: 'orion pictures',
    producers: ['r. j. louis'],
  },
  {
    title: 'Rambo III',
    year: 1988,
    award: false,
    studio: 'tristar pictures, carolco pictures',
    producers: ['buzz feitshans'],
  },
  {
    title: 'Star Trek V: The Final Frontier',
    year: 1989,
    award: true,
    studio: 'paramount pictures',
    producers: ['harve bennett'],
  },
  {
    title: 'The Karate Kid Part III',
    year: 1989,
    award: false,
    studio: 'columbia pictures',
    producers: ['jerry weintraub'],
  },
  {
    title: 'Lock Up',
    year: 1989,
    award: false,
    studio: 'tristar pictures, carolco pictures',
    producers: ['charles gordon', 'lawrence gordon'],
  },
  {
    title: 'Road House',
    year: 1989,
    award: false,
    studio: 'united artists',
    producers: ['joel silver'],
  },
  {
    title: 'Speed Zone',
    year: 1989,
    award: false,
    studio: 'orion pictures',
    producers: ['murray shostack'],
  },
  {
    title: 'The Adventures of Ford Fairlane',
    year: 1990,
    award: true,
    studio: '20th century fox',
    producers: ['steven perry', 'joel silver'],
  },
  {
    title: "Ghosts Can't Do It",
    year: 1990,
    award: true,
    studio: 'triumph releasing',
    producers: ['bo derek'],
  },
  {
    title: 'The Bonfire of the Vanities',
    year: 1990,
    award: false,
    studio: 'warner bros.',
    producers: ['brian de palma'],
  },
  {
    title: 'Graffiti Bridge',
    year: 1990,
    award: false,
    studio: 'warner bros.',
    producers: ['randy phillips', 'craig rice'],
  },
  {
    title: 'Rocky V',
    year: 1990,
    award: false,
    studio: 'united artists',
    producers: ['robert chartoff', 'irwin winkler'],
  },
  {
    title: 'Hudson Hawk',
    year: 1991,
    award: true,
    studio: 'tristar pictures',
    producers: ['joel silver'],
  },
  {
    title: 'Cool as Ice',
    year: 1991,
    award: false,
    studio: 'universal studios',
    producers: ['carolyn pfeiffer', 'lionel wingram'],
  },
  {
    title: 'Dice Rules',
    year: 1991,
    award: false,
    studio: 'seven arts productions',
    producers: ['loucas george'],
  },
  {
    title: 'Nothing but Trouble',
    year: 1991,
    award: false,
    studio: 'warner bros.',
    producers: ['lester berman', 'robert k. weiss'],
  },
  {
    title: 'Return to the Blue Lagoon',
    year: 1991,
    award: false,
    studio: 'columbia pictures',
    producers: ['william a. graham'],
  },
  {
    title: 'Shining Through',
    year: 1992,
    award: true,
    studio: '20th century fox',
    producers: ['carol baum', 'howard rosenman'],
  },
  {
    title: 'The Bodyguard',
    year: 1992,
    award: false,
    studio: 'warner bros.',
    producers: ['kevin costner', 'lawrence kasdan', 'jim wilson'],
  },
  {
    title: 'Christopher Columbus: The Discovery',
    year: 1992,
    award: false,
    studio: 'warner bros.',
    producers: ['alexander salkind', 'ilya salkind'],
  },
  {
    title: 'Final Analysis',
    year: 1992,
    award: false,
    studio: '20th century fox',
    producers: ['paul junger witt', 'charles roven', 'tony thomas'],
  },
  {
    title: 'Newsies',
    year: 1992,
    award: false,
    studio: 'walt disney pictures',
    producers: ['michael finnell'],
  },
  {
    title: 'Indecent Proposal',
    year: 1993,
    award: true,
    studio: 'paramount pictures',
    producers: ['sherry lansing'],
  },
  {
    title: 'Body of Evidence',
    year: 1993,
    award: false,
    studio: 'mgm, united artists',
    producers: ['dino de laurentiis'],
  },
  {
    title: 'Cliffhanger',
    year: 1993,
    award: false,
    studio: 'tristar pictures, carolco pictures',
    producers: ['renny harlin', 'alan marshall'],
  },
  {
    title: 'Last Action Hero',
    year: 1993,
    award: false,
    studio: 'columbia pictures',
    producers: ['john mctiernan', 'stephen j. roth'],
  },
  {
    title: 'Sliver',
    year: 1993,
    award: false,
    studio: 'paramount pictures',
    producers: ['robert evans'],
  },
  {
    title: 'Color of Night',
    year: 1994,
    award: true,
    studio: 'hollywood pictures',
    producers: ['buzz feitshans', 'david matalon'],
  },
  {
    title: 'North',
    year: 1994,
    award: false,
    studio: 'columbia pictures, castle rock entertainment',
    producers: ['rob reiner', 'alan zweibel'],
  },
  {
    title: 'On Deadly Ground',
    year: 1994,
    award: false,
    studio: 'warner bros.',
    producers: ['a. kitman ho', 'julius r. nasso', 'steven seagal'],
  },
  {
    title: 'The Specialist',
    year: 1994,
    award: false,
    studio: 'warner bros.',
    producers: ['jerry weintraub'],
  },
  {
    title: 'Wyatt Earp',
    year: 1994,
    award: false,
    studio: 'warner bros.',
    producers: ['kevin costner', 'lawrence kasdan', 'jim wilson'],
  },
  {
    title: 'Showgirls',
    year: 1995,
    award: true,
    studio: 'mgm, united artists',
    producers: ['charles evans', 'alan marshall'],
  },
  {
    title: 'Congo',
    year: 1995,
    award: false,
    studio: 'paramount pictures',
    producers: ['kathleen kennedy', 'sam mercer'],
  },
  {
    title: "It's Pat",
    year: 1995,
    award: false,
    studio: 'touchstone pictures',
    producers: ['charles b. wessler'],
  },
  {
    title: 'The Scarlet Letter',
    year: 1995,
    award: false,
    studio: 'hollywood pictures',
    producers: ['roland joffé', 'andrew g. vajna'],
  },
  {
    title: 'Waterworld',
    year: 1995,
    award: false,
    studio: 'universal studios',
    producers: [
      'kevin costner',
      'john davis',
      'charles gordon',
      'lawrence gordon',
    ],
  },
  {
    title: 'Striptease',
    year: 1996,
    award: true,
    studio: 'columbia pictures, castle rock entertainment',
    producers: ['andrew bergman', 'mike lobell'],
  },
  {
    title: 'Barb Wire',
    year: 1996,
    award: false,
    studio: 'polygram filmed entertainment, gramercy pictures',
    producers: ['todd moyer', 'mike richardson', 'brad wyman'],
  },
  {
    title: 'Ed',
    year: 1996,
    award: false,
    studio: 'universal studios',
    producers: ['rosalie swedlin'],
  },
  {
    title: 'The Island of Dr. Moreau',
    year: 1996,
    award: false,
    studio: 'new line cinema',
    producers: ['edward r. pressman'],
  },
  {
    title: 'The Stupids',
    year: 1996,
    award: false,
    studio: 'new line cinema, savoy pictures',
    producers: ['leslie belzberg'],
  },
  {
    title: 'The Postman',
    year: 1997,
    award: true,
    studio: 'warner bros.',
    producers: ['kevin costner', 'steve tisch', 'jim wilson'],
  },
  {
    title: 'Anaconda',
    year: 1997,
    award: false,
    studio: 'columbia pictures',
    producers: ['verna harrah', 'carole little', 'leonard rabinowitz'],
  },
  {
    title: 'Batman & Robin',
    year: 1997,
    award: false,
    studio: 'warner bros.',
    producers: ['peter macgregor-scott'],
  },
  {
    title: 'Fire Down Below',
    year: 1997,
    award: false,
    studio: 'warner bros.',
    producers: ['julius r. nasso', 'steven seagal'],
  },
  {
    title: 'Speed 2: Cruise Control',
    year: 1997,
    award: false,
    studio: '20th century fox',
    producers: ['jan de bont', 'steve perry', 'michael peyser'],
  },
  {
    title: 'An Alan Smithee Film: Burn Hollywood Burn',
    year: 1998,
    award: true,
    studio: 'hollywood pictures',
    producers: ['ben myron', 'joe eszterhas'],
  },
  {
    title: 'Armageddon',
    year: 1998,
    award: false,
    studio: 'touchstone pictures',
    producers: ['michael bay', 'jerry bruckheimer'],
  },
  {
    title: 'The Avengers',
    year: 1998,
    award: false,
    studio: 'warner bros.',
    producers: ['jerry weintraub'],
  },
  {
    title: 'Godzilla',
    year: 1998,
    award: false,
    studio: 'tristar pictures',
    producers: ['roland emmerich', 'dean devlin'],
  },
  {
    title: 'Spice World',
    year: 1998,
    award: false,
    studio: 'columbia pictures',
    producers: ['uri fruchtan', 'mark l. rosen', 'barnaby thompson'],
  },
  {
    title: 'Wild Wild West',
    year: 1999,
    award: true,
    studio: 'warner bros.',
    producers: ['jon peters', 'barry sonnenfeld'],
  },
  {
    title: 'Big Daddy',
    year: 1999,
    award: false,
    studio: 'columbia pictures',
    producers: ['sidney ganis', 'jack giarraputo'],
  },
  {
    title: 'The Blair Witch Project',
    year: 1999,
    award: false,
    studio: 'artisan entertainment',
    producers: ['robin cowie', 'gregg hale'],
  },
  {
    title: 'The Haunting',
    year: 1999,
    award: false,
    studio: 'dreamworks',
    producers: ['susan arthur', 'donna roth', 'colin wilson'],
  },
  {
    title: 'Star Wars: Episode I – The Phantom Menace',
    year: 1999,
    award: false,
    studio: '20th century fox',
    producers: ['rick mccallum', 'george lucas'],
  },
  {
    title: 'Battlefield Earth',
    year: 2000,
    award: true,
    studio: 'warner bros., franchise pictures',
    producers: ['jonathan d. krane', 'elie samaha', 'john travolta'],
  },
  {
    title: 'Book of Shadows: Blair Witch 2',
    year: 2000,
    award: false,
    studio: 'artisan entertainment',
    producers: ['bill carraro'],
  },
  {
    title: 'The Flintstones in Viva Rock Vegas',
    year: 2000,
    award: false,
    studio: 'universal studios',
    producers: ['bruce cohen'],
  },
  {
    title: 'Little Nicky',
    year: 2000,
    award: false,
    studio: 'new line cinema',
    producers: ['jack giarraputo', 'robert simonds'],
  },
  {
    title: 'The Next Best Thing',
    year: 2000,
    award: false,
    studio: 'paramount pictures',
    producers: ['leslie dixon', 'linne radmin', 'tom rosenberg'],
  },
  {
    title: 'Freddy Got Fingered',
    year: 2001,
    award: true,
    studio: '20th century fox',
    producers: ['larry brezner', 'howard lapides', 'lauren lloyd'],
  },
  {
    title: 'Driven',
    year: 2001,
    award: false,
    studio: 'warner bros., franchise pictures',
    producers: ['renny harlin', 'elie samaha', 'sylvester stallone'],
  },
  {
    title: 'Glitter',
    year: 2001,
    award: false,
    studio: '20th century fox, columbia pictures',
    producers: ['laurence mark', 'e. bennett walsh'],
  },
  {
    title: 'Pearl Harbor',
    year: 2001,
    award: false,
    studio: 'touchstone pictures',
    producers: ['michael bay', 'jerry bruckheimer'],
  },
  {
    title: '3000 Miles to Graceland',
    year: 2001,
    award: false,
    studio: 'warner bros., franchise pictures',
    producers: [
      'demian lichtenstein',
      'eric manes',
      'elie samaha',
      'richard spero',
      'andrew stevens',
    ],
  },
  {
    title: 'Swept Away',
    year: 2002,
    award: true,
    studio: 'screen gems',
    producers: ['matthew vaughn'],
  },
  {
    title: 'The Adventures of Pluto Nash',
    year: 2002,
    award: false,
    studio: 'warner bros.',
    producers: ['martin bregman', 'michael scott bregman', 'louis a. stroller'],
  },
  {
    title: 'Crossroads',
    year: 2002,
    award: false,
    studio: 'paramount pictures',
    producers: ['ann carli'],
  },
  {
    title: 'Pinocchio',
    year: 2002,
    award: false,
    studio: 'miramax films',
    producers: ['gianluigi braschi', 'nicoletta braschi', 'elda ferri'],
  },
  {
    title: 'Star Wars: Episode II – Attack of the Clones',
    year: 2002,
    award: false,
    studio: '20th century fox',
    producers: ['rick mccallum', 'george lucas'],
  },
  {
    title: 'Gigli',
    year: 2003,
    award: true,
    studio: 'columbia pictures, revolution studios',
    producers: ['martin brest', 'casey silver'],
  },
  {
    title: 'The Cat in the Hat',
    year: 2003,
    award: false,
    studio: 'universal studios, dreamworks',
    producers: ['brian grazer'],
  },
  {
    title: "Charlie's Angels: Full Throttle",
    year: 2003,
    award: false,
    studio: 'columbia pictures',
    producers: ['drew barrymore', 'leonard goldberg', 'nancy juvonen'],
  },
  {
    title: 'From Justin to Kelly',
    year: 2003,
    award: false,
    studio: '20th century fox',
    producers: ['john steven agoglia'],
  },
  {
    title: 'The Real Cancun',
    year: 2003,
    award: false,
    studio: 'new line cinema',
    producers: [
      'mary-ellis bunim',
      'jonathan murray',
      'jamie schutz',
      'rick de oliveira',
    ],
  },
  {
    title: 'Catwoman',
    year: 2004,
    award: true,
    studio: 'warner bros.',
    producers: ['denise di novi', 'edward mcdonnell'],
  },
  {
    title: 'Alexander',
    year: 2004,
    award: false,
    studio: 'warner bros.',
    producers: ['moritz borman', 'jon kilik', 'thomas schuhly', 'iain smith'],
  },
  {
    title: 'Superbabies: Baby Geniuses 2',
    year: 2004,
    award: false,
    studio: 'triumph films',
    producers: ['steven paul'],
  },
  {
    title: 'Surviving Christmas',
    year: 2004,
    award: false,
    studio: 'dreamworks',
    producers: ['betty thomas', 'jenno topping'],
  },
  {
    title: 'White Chicks',
    year: 2004,
    award: false,
    studio: 'columbia pictures, revolution studios',
    producers: [
      'rick alvarez',
      'lee r. mayes',
      'keenen ivory wayans',
      'marlon wayans',
      'shawn wayans',
    ],
  },
  {
    title: 'Dirty Love',
    year: 2005,
    award: true,
    studio: 'first look pictures',
    producers: [
      'john mallory asher',
      'bj davis',
      'rod hamilton',
      'kimberley kates',
      'michael manasseri',
      'jenny mccarthy',
      'trent walford',
    ],
  },
  {
    title: 'Deuce Bigalow: European Gigolo',
    year: 2005,
    award: false,
    studio: 'columbia pictures',
    producers: ['adam sandler', 'rob schneider'],
  },
  {
    title: 'The Dukes of Hazzard',
    year: 2005,
    award: false,
    studio: 'warner bros., village roadshow',
    producers: ['bill gerber'],
  },
  {
    title: 'House of Wax',
    year: 2005,
    award: false,
    studio: 'warner bros., village roadshow',
    producers: ['susan levin', 'joel silver', 'robert zemeckis'],
  },
  {
    title: 'Son of the Mask',
    year: 2005,
    award: false,
    studio: 'new line cinema',
    producers: ['erica huggins', 'scott kroopf'],
  },
  {
    title: 'Basic Instinct 2',
    year: 2006,
    award: true,
    studio: 'mgm, c2 pictures',
    producers: ['mario kassar', 'joel b. michaels', 'andrew g. vajna'],
  },
  {
    title: 'BloodRayne',
    year: 2006,
    award: false,
    studio: 'romar entertainment',
    producers: ['uwe boll', 'dan clarke', 'wolfgang herrold'],
  },
  {
    title: 'Lady in the Water',
    year: 2006,
    award: false,
    studio: 'warner bros.',
    producers: ['sam mercer', 'jose l. rodriguez', 'm. night shyamalan'],
  },
  {
    title: 'Little Man',
    year: 2006,
    award: false,
    studio: 'columbia pictures, revolution studios',
    producers: ['rick alvares', 'lee mays', 'marlon wayans', 'shawn wayans'],
  },
  {
    title: 'The Wicker Man',
    year: 2006,
    award: false,
    studio: 'warner bros.',
    producers: [
      'nicolas cage',
      'randall emmett',
      'norm golightly',
      'avi lerner',
      'joanne sellar',
    ],
  },
  {
    title: 'I Know Who Killed Me',
    year: 2007,
    award: false,
    studio: 'tristar pictures',
    producers: ['david grace', 'frank mancuso jr.'],
  },
  {
    title: 'Bratz',
    year: 2007,
    award: false,
    studio: 'lionsgate',
    producers: ['avi arad', 'isaac larian', 'steven paul'],
  },
  {
    title: 'Daddy Day Camp',
    year: 2007,
    award: false,
    studio: 'tristar pictures, revolution studios',
    producers: ['matt berenson', 'john davis', 'wyck godfrey'],
  },
  {
    title: 'I Now Pronounce You Chuck & Larry',
    year: 2007,
    award: false,
    studio: 'universal studios',
    producers: ['adam sandler', 'tom shadyac'],
  },
  {
    title: 'Norbit',
    year: 2007,
    award: false,
    studio: 'dreamworks',
    producers: ['john davis', 'eddie murphy', 'michael tollin'],
  },
  {
    title: 'The Love Guru',
    year: 2008,
    award: true,
    studio: 'paramount pictures',
    producers: ['gary barber', 'michael deluca', 'mike myers'],
  },
  {
    title: 'Disaster Movie and Meet the Spartans',
    year: 2008,
    award: false,
    studio: 'lionsgate, 20th century fox',
    producers: ['jason friedberg', 'peter safran', 'aaron seltzer'],
  },
  {
    title: 'The Happening',
    year: 2008,
    award: false,
    studio: '20th century fox',
    producers: ['barry mendel', 'sam mercer', 'm. night shyamalan'],
  },
  {
    title: 'The Hottie & the Nottie',
    year: 2008,
    award: false,
    studio: 'regent releasing',
    producers: ['hadeel reda'],
  },
  {
    title: 'In the Name of the King',
    year: 2008,
    award: false,
    studio: 'boll kg, brightlight pictures',
    producers: [
      'uwe boll',
      'dan clarke',
      'wolfgang herrold',
      'shawn williamson',
    ],
  },
  {
    title: 'Transformers: Revenge of the Fallen',
    year: 2009,
    award: true,
    studio: 'paramount pictures, dreamworks, hasbro',
    producers: [
      'lorenzo di bonaventura',
      'ian bryce',
      'tom desanto',
      'don murphy',
    ],
  },
  {
    title: 'All About Steve',
    year: 2009,
    award: false,
    studio: '20th century fox',
    producers: ['sandra bullock', 'mary mclaglen'],
  },
  {
    title: 'G.I. Joe: The Rise of Cobra',
    year: 2009,
    award: false,
    studio: 'paramount pictures, hasbro',
    producers: ['lorenzo di bonaventura', 'bob ducsay', 'brian goldner'],
  },
  {
    title: 'Land of the Lost',
    year: 2009,
    award: false,
    studio: 'universal studios',
    producers: ['sid', 'marty krofft', 'jimmy miller'],
  },
  {
    title: 'Old Dogs',
    year: 2009,
    award: false,
    studio: 'walt disney pictures',
    producers: ['peter abrams', 'robert levy', 'andrew panay'],
  },
  {
    title: 'The Last Airbender',
    year: 2010,
    award: true,
    studio: 'paramount pictures, nickelodeon movies',
    producers: [
      'frank marshall',
      'kathleen kennedy',
      'sam mercer',
      'm. night shyamalan',
    ],
  },
  {
    title: 'The Bounty Hunter',
    year: 2010,
    award: false,
    studio: 'columbia pictures',
    producers: ['neal h. moritz'],
  },
  {
    title: 'Sex and the City 2',
    year: 2010,
    award: false,
    studio: 'new line cinema, hbo films, village roadshow pictures',
    producers: [
      'michael patrick king',
      'john melfi',
      'sarah jessica parker',
      'darren star',
    ],
  },
  {
    title: 'The Twilight Saga: Eclipse',
    year: 2010,
    award: false,
    studio: 'summit entertainment',
    producers: ['wyck godfrey', 'karen rosenfelt'],
  },
  {
    title: 'Vampires Suck',
    year: 2010,
    award: false,
    studio: '20th century fox',
    producers: ['jason friedberg', 'peter safran', 'aaron seltzer'],
  },
  {
    title: 'Jack and Jill',
    year: 2011,
    award: true,
    studio: 'columbia pictures',
    producers: ['todd garner', 'jack giarraputo', 'adam sandler'],
  },
  {
    title: 'Bucky Larson: Born to Be a Star',
    year: 2011,
    award: false,
    studio: 'columbia pictures',
    producers: [
      'barry bernardi',
      'allen covert',
      'david dorfman',
      'jack giarraputo',
    ],
  },
  {
    title: "New Year's Eve",
    year: 2011,
    award: false,
    studio: 'warner bros., new line cinema',
    producers: ['mike karz', 'garry marshall', 'wayne allan rice'],
  },
  {
    title: 'Transformers: Dark of the Moon',
    year: 2011,
    award: false,
    studio: 'paramount pictures',
    producers: [
      'lorenzo di bonaventura',
      'ian bryce',
      'tom desanto',
      'don murphy',
    ],
  },
  {
    title: 'The Twilight Saga: Breaking Dawn – Part 1',
    year: 2011,
    award: false,
    studio: 'summit entertainment',
    producers: ['wyck godfrey', 'stephenie meyer', 'karen rosenfelt'],
  },
  {
    title: 'The Twilight Saga: Breaking Dawn – Part 2',
    year: 2012,
    award: true,
    studio: 'summit entertainment',
    producers: ['wyck godfrey', 'stephenie meyer', 'karen rosenfelt'],
  },
  {
    title: 'Battleship',
    year: 2012,
    award: false,
    studio: 'universal studios',
    producers: [
      'sarah aubrey',
      'peter berg',
      'brian goldner',
      'duncan henderson',
      'bennett schneir',
      'scott stuber',
    ],
  },
  {
    title: 'The Oogieloves in the Big Balloon Adventure',
    year: 2012,
    award: false,
    studio: 'lionsgate films, romar entertainment, kenn viselman presents',
    producers: ['gayle dickie', 'kenn viselman'],
  },
  {
    title: "That's My Boy",
    year: 2012,
    award: false,
    studio: 'columbia pictures',
    producers: [
      'allen covert',
      'jack giarraputo',
      'heather parry',
      'adam sandler',
    ],
  },
  {
    title: 'A Thousand Words',
    year: 2012,
    award: false,
    studio: 'paramount pictures, dreamworks',
    producers: [
      'nicolas cage',
      'alain chabat',
      'stephanie danan',
      'norman golightly',
      'brian robbinsand sharla sumpter bridgett',
    ],
  },
  {
    title: 'Movie 43',
    year: 2013,
    award: true,
    studio: 'relativity media',
    producers: [
      'peter farrelly',
      'ryan kavanaugh',
      'john penotti',
      'charles b. wessler',
    ],
  },
  {
    title: 'After Earth',
    year: 2013,
    award: false,
    studio: 'columbia pictures',
    producers: [
      'james lassiter',
      'caleeb pinkett',
      'jada pinkett smith',
      'm. night shyamalan',
      'will smith',
      'jaden smith',
    ],
  },
  {
    title: 'Grown Ups 2',
    year: 2013,
    award: false,
    studio: 'columbia pictures',
    producers: ['jack giarraputo', 'adam sandler'],
  },
  {
    title: 'The Lone Ranger',
    year: 2013,
    award: false,
    studio: 'walt disney pictures',
    producers: ['jerry bruckheimer', 'gore verbinski'],
  },
  {
    title: 'A Madea Christmas',
    year: 2013,
    award: false,
    studio: 'lionsgate',
    producers: ['ozzie areu', 'matt moore', 'tyler perry'],
  },
  {
    title: 'Saving Christmas',
    year: 2014,
    award: true,
    studio: 'samuel goldwyn films',
    producers: [
      'darren doane',
      'raphi henley',
      'amanda rosser',
      'david shannon',
    ],
  },
  {
    title: 'Left Behind',
    year: 2014,
    award: false,
    studio: 'freestyle releasing, entertainment one',
    producers: ['michael walker', 'paul lalonde'],
  },
  {
    title: 'The Legend of Hercules',
    year: 2014,
    award: false,
    studio: 'summit entertainment',
    producers: ['boaz davidson', 'renny harlin', 'danny lerner', 'les weldon'],
  },
  {
    title: 'Teenage Mutant Ninja Turtles',
    year: 2014,
    award: false,
    studio: 'paramount pictures, nickelodeon movies, platinum dunes',
    producers: [
      'michael bay',
      'ian bryce',
      'andrew form',
      'bradley fuller',
      'scott mednick',
      'galen walker',
    ],
  },
  {
    title: 'Transformers: Age of Extinction',
    year: 2014,
    award: false,
    studio: 'paramount pictures',
    producers: [
      'ian bryce',
      'tom desanto',
      'lorenzo di bonaventura',
      'don murphy',
    ],
  },
  {
    title: 'Fantastic Four',
    year: 2015,
    award: true,
    studio: '20th century fox',
    producers: [
      'simon kinberg',
      'matthew vaughn',
      'hutch parker',
      'robert kulzer',
      'gregory goodman',
    ],
  },
  {
    title: 'Fifty Shades of Grey',
    year: 2015,
    award: true,
    studio: 'universal pictures, focus features',
    producers: ['michael de luca', 'dana brunetti', 'e. l. james'],
  },
  {
    title: 'Jupiter Ascending',
    year: 2015,
    award: false,
    studio: 'warner bros.',
    producers: ['grant hill', 'the wachowskis'],
  },
  {
    title: 'Paul Blart: Mall Cop 2',
    year: 2015,
    award: false,
    studio: 'columbia pictures',
    producers: ['todd garner', 'kevin james', 'adam sandler'],
  },
  {
    title: 'Pixels',
    year: 2015,
    award: false,
    studio: 'columbia pictures',
    producers: [
      'adam sandler',
      'chris columbus',
      'mark radcliffe',
      'allen covert',
    ],
  },
  {
    title: "Hillary's America: The Secret History of the Democratic Party",
    year: 2016,
    award: true,
    studio: 'quality flix',
    producers: ['gerald r. molen'],
  },
  {
    title: 'Batman v Superman: Dawn of Justice',
    year: 2016,
    award: false,
    studio: 'warner bros.',
    producers: ['charles roven', 'deborah snyder'],
  },
  {
    title: 'Dirty Grandpa',
    year: 2016,
    award: false,
    studio: 'lionsgate',
    producers: [
      'bill block',
      'michael simkin',
      'jason barrett',
      'barry josephson',
    ],
  },
  {
    title: 'Gods of Egypt',
    year: 2016,
    award: false,
    studio: 'summit entertainment',
    producers: ['basil iwanyk', 'alex proyas'],
  },
  {
    title: 'Independence Day: Resurgence',
    year: 2016,
    award: false,
    studio: '20th century fox',
    producers: ['dean devlin', 'harald kloser', 'roland emmerich'],
  },
  {
    title: 'Zoolander 2',
    year: 2016,
    award: false,
    studio: 'paramount pictures',
    producers: [
      'stuart cornfeld',
      'scott rudin',
      'ben stiller',
      'clayton townsend',
    ],
  },
  {
    title: 'The Emoji Movie',
    year: 2017,
    award: true,
    studio: 'columbia pictures',
    producers: ['michelle raimo kouyate'],
  },
  {
    title: 'Baywatch',
    year: 2017,
    award: false,
    studio: 'paramount pictures',
    producers: [
      'ivan reitman',
      'michael berk',
      'douglas schwartz',
      'gregory j. bonann',
      'beau flynn',
    ],
  },
  {
    title: 'Fifty Shades Darker',
    year: 2017,
    award: false,
    studio: 'universal pictures',
    producers: [
      'michael de luca',
      'e. l. james',
      'dana brunetti',
      'marcus viscidi',
    ],
  },
  {
    title: 'The Mummy',
    year: 2017,
    award: false,
    studio: 'universal pictures',
    producers: [
      'alex kurtzman',
      'chris morgan',
      'sean daniel',
      'sarah bradshaw',
    ],
  },
  {
    title: 'Transformers: The Last Knight',
    year: 2017,
    award: false,
    studio: 'paramount pictures',
    producers: [
      'don murphy',
      'tom desanto',
      'lorenzo di bonaventura',
      'ian bryce',
    ],
  },
  {
    title: 'Holmes & Watson',
    year: 2018,
    award: true,
    studio: 'columbia pictures',
    producers: [
      'will ferrell',
      'adam mckay',
      'jimmy miller',
      'clayton townsend',
    ],
  },
  {
    title: 'Gotti',
    year: 2018,
    award: false,
    studio: 'vertical entertainment',
    producers: [
      'randall emmett',
      'marc fiore',
      'michael froch',
      'george furla',
    ],
  },
  {
    title: 'The Happytime Murders',
    year: 2018,
    award: false,
    studio: 'stx',
    producers: [
      'ben falcone',
      'jeffrey hayes',
      'brian henson',
      'melissa mccarthy',
    ],
  },
  {
    title: 'Robin Hood',
    year: 2018,
    award: false,
    studio: 'summit entertainment',
    producers: ['jennifer davisson', 'leonardo dicaprio'],
  },
  {
    title: 'Winchester',
    year: 2018,
    award: false,
    studio: 'lionsgate',
    producers: ['tim mcgahan', 'brett tomberlin'],
  },
  {
    title: 'Cats',
    year: 2019,
    award: true,
    studio: 'universal pictures',
    producers: ['debra hayward', 'tim bevan', 'eric fellner', 'tom hooper'],
  },
  {
    title: 'The Fanatic',
    year: 2019,
    award: false,
    studio: 'quiver distribution',
    producers: ['daniel grodnik', 'oscar generale', 'bill kenwright'],
  },
  {
    title: 'The Haunting of Sharon Tate',
    year: 2019,
    award: false,
    studio: 'saban films',
    producers: ['lucas jarach', 'daniel farrands', 'eric brenner'],
  },
  {
    title: 'A Madea Family Funeral',
    year: 2019,
    award: false,
    studio: 'lionsgate',
    producers: ['ozzie areu', 'will areu', 'mark e. swinton'],
  },
  {
    title: 'Rambo: Last Blood',
    year: 2019,
    award: false,
    studio: 'lionsgate',
    producers: [
      'avi lerner',
      'kevin king templeton',
      'yariv lerner',
      'les weldon',
    ],
  },
];
